### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SteveDiamond** [oxfordcontrol/osqp#167]
I had an issue recently installing OSQP 0.5.0 with Python 3.7 on Linux. Any ideas?
```
Installed /home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/six-1.12.0-py3.7.egg
Searching for osqp>=0.4.1
Reading https://pypi.org/simple/osqp/
Downloading https://files.pythonhosted.org/packages/a3/4b/cd8f95cd975c93f3a28ea11d06a5e4bd42154629bef5287262364eaad161/osqp-0.5.0.tar.gz#sha256=86d58b5a9f8f4dc6fd1dcb02fbb29be8c3bcae59b85620d174c88125d953707d
Best match: osqp 0.5.0
Processing osqp-0.5.0.tar.gz
Writing /tmp/easy_install-1i716cyy/osqp-0.5.0/setup.cfg
Running osqp-0.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1i716cyy/osqp-0.5.0/egg-dist-tmp-y8h5d3y1
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-1i716cyy/osqp-0.5.0/setup.py", line 217, in <module>
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-1i716cyy/osqp-0.5.0/setup.py", line 146, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

**Comment by bstellato** [comment]
Thanks for reporting it! I think this is related to [this line](https://github.com/oxfordcontrol/osqp-python/blob/0363d028b2321017049360d2eb3c0cf206028c43/setup.py#L146). It was introduced by [this PR](https://github.com/oxfordcontrol/osqp-python/pull/2) to avoid having numpy at the top of setup.py. 

@ali5h since you made that PR, do you know how to fix those changes in python 3.7 with the new distutils/setuptools?

**Comment by ali5h** [comment]
yes, we can use `pyproject.toml` . I submitted the same change for cvxpy, will open a pr, cheers

**Comment by bstellato** [comment]
After lots of pain I managed to get continuous CI and Deployment to work on osqp-python. Could you please check if this works with `pip install -i https://test.pypi.org/simple/ osqp==0.6.0.dev17` ?

**Comment by SteveDiamond** [comment]
I can't really try that on Travis, but it works on my local machine.

**Comment by bstellato** [comment]
Ok thanks! I will close it for now. In case feel free to reopen it.
