### ISSUE TITLE
osqp-0.6.0 Python package is missing requirements.txt

### ISSUE THREAD

**Issue by sebp** [oxfordcontrol/osqp#182]
osqp 0.6.0 currently cannot be installed, because the source distribution does not contain an requirements.txt, which is read by setup.py, which results in the error below:

```
Collecting osqp (from cvxpy<1.0.16,>=1.0)
  Downloading https://files.pythonhosted.org/packages/4e/df/545fb5d7042af343ccce15259575142f288c8728a83a64ac4faddea9f737/osqp-0.6.0.tar.gz (211kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-ckv8bae_\osqp\setup.py", line 205, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by bstellato** [comment]
Thanks! I am working for a couple of fixes in the python interface. I will make a fix today.

**Comment by bstellato** [comment]
It should be fixed now with the latest python version. Can you please try it?

**Comment by sebp** [comment]
Yes it works now. Thanks for fixing it quickly.
