### ISSUE TITLE
 import osqp fails for me

### ISSUE THREAD

**Issue by oakleaflr** [oxfordcontrol/osqp#59]
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import sys
>>> print(sys.version)
3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
>>> import osqp
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import osqp
  File "C:\Users\Joann\AppData\Local\Programs\Python\Python36\lib\site-packages\osqp\__init__.py", line 1, in <module>
    from osqp.interface import OSQP
  File "C:\Users\Joann\AppData\Local\Programs\Python\Python36\lib\site-packages\osqp\interface.py", line 6, in <module>
    import osqp._osqp as _osqp  # Internal low level module
ImportError: numpy.core.multiarray failed to import
>>> import numpy
>>>

**Comment by goulart-paul** [comment]
Perhaps your version of numpy is out of date?   You could try:

`pip install numpy --upgrade `

A similar sounding problem is described here : https://stackoverflow.com/questions/33859531/runtimeerror-module-compiled-against-api-version-a-but-this-version-of-numpy-is

**Comment by oakleaflr** [comment]
Isn't computing fun???!!!  It gets better toward the end.


C:\Users\Joann>pip install numpy --upgrade
Collecting numpy
  Downloading numpy-1.14.2-cp36-none-win_amd64.whl (13.4MB)
    100% |████████████████████████████████| 13.4MB 23kB/s
Installing collected packages: numpy
  Found existing installation: numpy 1.13.3
    Uninstalling numpy-1.13.3:
      Successfully uninstalled numpy-1.13.3
Exception:
Traceback (most recent call last):
  File "c:\users\joann\appdata\local\programs\python\python36\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Joann\\AppData\\Local\\Temp\\pip-srbn7cku-uninstall\\users\\joann\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\numpy\\core\\libopenblas_v0.2.20_mingwpy.dll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 795, in install
    requirement.commit_uninstall()
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\joann\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 7 more times]
  File "c:\users\joann\appdata\local\programs\python\python36\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\joann\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Joann\\AppData\\Local\\Temp\\pip-srbn7cku-uninstall\\users\\joann\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\numpy\\core\\libopenblas_v0.2.20_mingwpy.dll'

C:\Users\Joann>pip install numpy --upgrade
Requirement already up-to-date: numpy in c:\users\joann\appdata\local\programs\python\python36\lib\site-packages

C:\Users\Joann>

Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import numpy as np
>>> import osqp
>>> import scipy.sparse as sparse
>>> P = sparse.csc_matrix([[4, 1], [1, 2]])
>>> q = np.array([1, 1])
>>> A = sparse.csc_matrix([[1, 1], [1, 0], [0, 1]])
>>> l = np.array([1, 0, 0])
>>> u = np.array([1, 0.7, 0.7])

>>> prob = osqp.OSQP()

>>> prob.setup(P, q, A, l, u, alpha=1.0)

-----------------------------------------------------------------
           OSQP v0.3.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2017
-----------------------------------------------------------------
problem:  variables n = 2, constraints m = 3
          nnz(P) + nnz(A) = 10
settings: linear system solver = suitesparse ldl,
          eps_abs = 1.0e-03, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.00, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off

>>> res = prob.solve()
iter  objective    pri res    dua res    rho        time
   1  -4.9384e-03   1.00e+00   2.00e+02   1.00e-01   5.48e-02s
  50   1.8800e+00   1.91e-07   7.50e-07   1.38e+00   7.23e-02s

status:               solved
number of iterations: 50
optimal objective:    1.8800
run time:             8.82e-02s
optimal rho estimate: 1.36e+00

>>>

**Comment by oakleaflr** [comment]
Thanks.  This worked.
